import {
  LayoutDashboard,
  Car,
  Calendar,
  MapPin,
  User,
  UserCog,
  Settings,
  LogOut,
  Clock,
  Check,
  Loader,
  Search,
  Plus,
  Pencil,
  Trash,
  ChevronDown,
  ChevronUp,
  ChevronLeft,
  ChevronRight,
  MoreHorizontal,
  X,
  Menu,
  Eye,
} from "lucide-react";
import { SiGoogle } from 'react-icons/si';

export const Icons = {
  dashboard: LayoutDashboard,
  car: Car,
  calendar: Calendar,
  location: MapPin,
  user: User,
  userSettings: UserCog,
  settings: Settings,
  logout: LogOut,
  time: Clock,
  check: Check,
  spinner: Loader,
  search: Search,
  plus: Plus,
  edit: Pencil,
  delete: Trash,
  chevronDown: ChevronDown,
  chevronUp: ChevronUp,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  more: MoreHorizontal,
  close: X,
  menu: Menu,
  view: Eye,
  google: SiGoogle,
};
